import type { UpsertVendorPackageBody, VendorCategory } from "@ceylonweddings/contracts";

type TemplatePackage = UpsertVendorPackageBody;

const PHOTO: TemplatePackage[] = [
  {
    name: "Ceremony coverage",
    pricingMode: "FROM",
    priceLkr: 150000,
    status: "DRAFT",
    sortOrder: 0,
    badge: null,
    inclusions: ["Poruwa / ceremony", "One shooter", "Edited online gallery"],
    exclusions: ["Album", "Drone"],
    eventTypes: ["WEDDING", "PORUWA"],
    durationHours: 6,
    guestMin: null,
    guestMax: null,
    photoUrls: [],
    bestFor: "Intimate ceremony",
    addOnIds: [],
    tier: "BASIC",
    description: "Focused ceremony coverage with a clean highlight set.",
  },
  {
    name: "Day + film",
    pricingMode: "FROM",
    priceLkr: 280000,
    status: "DRAFT",
    sortOrder: 1,
    badge: "POPULAR",
    inclusions: ["Full day", "Two shooters", "Highlight film", "USB + online"],
    exclusions: ["Printed album"],
    eventTypes: ["WEDDING", "HOMECOMING"],
    durationHours: 10,
    guestMin: null,
    guestMax: null,
    photoUrls: [],
    bestFor: "Most couples",
    addOnIds: [],
    tier: "ADVANCED",
    description: "Poruwa, reception, and a cinematic highlight film.",
  },
];

const VENUE: TemplatePackage[] = [
  {
    name: "Hall hire",
    pricingMode: "FROM",
    priceLkr: 650000,
    status: "DRAFT",
    sortOrder: 0,
    badge: null,
    inclusions: ["Hall to 22:00", "Poruwa platform", "Bridal suite"],
    exclusions: ["Catering", "Decor"],
    eventTypes: ["WEDDING"],
    durationHours: 8,
    guestMin: 100,
    guestMax: 250,
    photoUrls: [],
    bestFor: "Venue-only bookings",
    addOnIds: [],
    tier: "BASIC",
    description: "Garden or ballroom hire with core wedding amenities.",
  },
  {
    name: "Hall + plates",
    pricingMode: "PER_GUEST",
    priceLkr: 8500,
    status: "DRAFT",
    sortOrder: 1,
    badge: "POPULAR",
    inclusions: ["Hall hire", "Buffet / plated", "Service staff"],
    exclusions: ["Alcohol packages"],
    eventTypes: ["WEDDING", "HOMECOMING"],
    durationHours: 8,
    guestMin: 150,
    guestMax: 400,
    photoUrls: [],
    bestFor: "100–300 guests",
    addOnIds: [],
    tier: "ADVANCED",
    description: "Venue with catering — priced per guest.",
  },
];

const MAKEUP: TemplatePackage[] = [
  {
    name: "Bridal trial",
    pricingMode: "FIXED",
    priceLkr: 25000,
    status: "DRAFT",
    sortOrder: 0,
    badge: null,
    inclusions: ["Hair + makeup trial", "Touch-up kit tips"],
    exclusions: ["On-location", "Draping"],
    eventTypes: ["ENGAGEMENT", "WEDDING"],
    durationHours: 2,
    guestMin: null,
    guestMax: null,
    photoUrls: [],
    bestFor: "Before the big day",
    addOnIds: [],
    tier: "BASIC",
    description: "Studio trial to lock your bridal look.",
  },
  {
    name: "Bridal day",
    pricingMode: "FROM",
    priceLkr: 65000,
    status: "DRAFT",
    sortOrder: 1,
    badge: "POPULAR",
    inclusions: ["On-location bridal", "Touch-ups", "False lashes"],
    exclusions: ["Bridesmaids"],
    eventTypes: ["WEDDING", "HOMECOMING"],
    durationHours: 4,
    guestMin: null,
    guestMax: null,
    photoUrls: [],
    bestFor: "Wedding morning",
    addOnIds: [],
    tier: "ADVANCED",
    description: "Full bridal glam on location.",
  },
];

const CATERING: TemplatePackage[] = [
  {
    name: "Classic buffet",
    pricingMode: "PER_GUEST",
    priceLkr: 4500,
    status: "DRAFT",
    sortOrder: 0,
    badge: null,
    inclusions: ["Buffet stations", "Service staff", "Cutlery"],
    exclusions: ["Alcohol", "Dessert table"],
    eventTypes: ["WEDDING", "HOMECOMING"],
    durationHours: null,
    guestMin: 100,
    guestMax: 500,
    photoUrls: [],
    bestFor: "Large receptions",
    addOnIds: [],
    tier: "BASIC",
    description: "Crowd-pleasing Sri Lankan + international buffet.",
  },
  {
    name: "Premium plates",
    pricingMode: "PER_GUEST",
    priceLkr: 7500,
    status: "DRAFT",
    sortOrder: 1,
    badge: "BEST_VALUE",
    inclusions: ["Plated service", "Live stations", "Kids meals"],
    exclusions: [],
    eventTypes: ["WEDDING"],
    durationHours: null,
    guestMin: 80,
    guestMax: 300,
    photoUrls: [],
    bestFor: "Sit-down dinners",
    addOnIds: [],
    tier: "ADVANCED",
    description: "Elevated plated menu with live cooking.",
  },
];

const DECOR: TemplatePackage[] = [
  {
    name: "Poruwa + entrance",
    pricingMode: "FROM",
    priceLkr: 120000,
    status: "DRAFT",
    sortOrder: 0,
    badge: null,
    inclusions: ["Poruwa florals", "Entrance arch", "Setup + teardown"],
    exclusions: ["Table centrepieces"],
    eventTypes: ["PORUWA", "WEDDING"],
    durationHours: null,
    guestMin: null,
    guestMax: null,
    photoUrls: [],
    bestFor: "Ceremony focus",
    addOnIds: [],
    tier: "BASIC",
    description: "Signature poruwa and welcome florals.",
  },
  {
    name: "Full reception decor",
    pricingMode: "FROM",
    priceLkr: 350000,
    status: "DRAFT",
    sortOrder: 1,
    badge: "POPULAR",
    inclusions: ["Poruwa", "Stage", "Tables (up to 20)", "Car decor"],
    exclusions: ["Ceiling installs"],
    eventTypes: ["WEDDING", "HOMECOMING"],
    durationHours: null,
    guestMin: null,
    guestMax: null,
    photoUrls: [],
    bestFor: "Full venue look",
    addOnIds: [],
    tier: "ADVANCED",
    description: "End-to-end floral and decor story.",
  },
];

const BY_CATEGORY: Partial<Record<VendorCategory, TemplatePackage[]>> = {
  PHOTO_VIDEO: PHOTO,
  VENUE: VENUE,
  HAIR_MAKEUP: MAKEUP,
  BRIDAL_DRESSER: MAKEUP,
  CATERER: CATERING,
  FLORIST_DECOR: DECOR,
};

export function offerTemplatesForCategory(category: VendorCategory): TemplatePackage[] {
  const templates = BY_CATEGORY[category];
  if (!templates?.length) return [];
  return templates.map((pkg, index) => ({
    ...pkg,
    sortOrder: index,
    addOnIds: [],
    photoUrls: [],
  }));
}

export const TEMPLATE_LABELS: Partial<Record<VendorCategory, string>> = {
  PHOTO_VIDEO: "Photography starter",
  VENUE: "Venue starter",
  HAIR_MAKEUP: "Makeup starter",
  BRIDAL_DRESSER: "Bridal dresser starter",
  CATERER: "Catering starter",
  FLORIST_DECOR: "Decor starter",
};
